UI/header
lmsGenie/lms-app pull request #43
Opened 2023-09-03 14:56 UTC by sub1120

2023-09-03 16:15 UTC, shivamvijaywargi requested changes
Please read the comments I have left.

2023-09-03 16:15 UTC, shivamvijaywargi commented on src/app/layout.tsx
> +          <Header></Header>
You can have a self closing tag.

2023-09-03 16:15 UTC, shivamvijaywargi commented on src/app/layout.tsx
> +import "./globals.css";
Double import?

2023-09-04 02:20 UTC, sub1120 commented on src/app/layout.tsx
> +          <Header></Header>
Corrected, please review

2023-09-04 02:20 UTC, sub1120 commented on src/app/layout.tsx
> +import "./globals.css";
Corrected, please review

2023-09-04 03:17 UTC, shivamvijaywargi approved these changes
Looks good

2023-09-04 03:17 UTC, merged