UI/contact us
lmsGenie/lms-app pull request #78
Opened 2023-10-19 18:15 UTC by Vinay-Pratap-Singh

### Describe your changes

Created the contact us page

### Issue ticket number and link

Write here...

### Please confirm the below message,

- [ ] I confirm that I have performed a self-review of my code, and written explainable comments in the code, the UI is rendered without any errors, the UI is responsive, dark mode UI is implemented, removed all debug-related code.

2023-10-19 18:16 UTC, Vinay-Pratap-Singh commented
@sub1120 please have a look and tell me the review so that I can move with other stuffs

2023-10-19 18:47 UTC, sub1120 commented
> @sub1120 please have a look and tell me the review so that I can move with other stuffs

Hello @Vinay-Pratap-Singh, Thanks for your active contribution. Sorry, but this PR is too long to review. It is always easier to review and merge small PRs, and If we move this fast, we may end up missing small things behind. Could you please create separate PRs for different sections of UI?

Also, we are planning to setup testing before we move further in UI development. I have already created an issue #73  for it, if you or any of your friend have any idea about "How to setup UI Testing", please have a look upon it.

2023-10-20 08:09 UTC, shivamvijaywargi commented
> > @sub1120 please have a look and tell me the review so that I can move with other stuffs
> 
> Hello @Vinay-Pratap-Singh, Thanks for your active contribution. Sorry, but this PR is too long to review. It is always easier to review and merge small PRs, and If we move this fast, we may end up missing small things behind. Could you please create separate PRs for different sections of UI?
> 
> Also, we are planning to setup testing before we move further in UI development. I have already created an issue #73 for it, if you or any of your friend have any idea about "How to setup UI Testing", please have a look upon it.

I like this idea, but let it slide this one time since it is already done.

Let's review this and merge and from next time onwards @Vinay-Pratap-Singh please keep the PRs short.

2023-10-20 08:12 UTC, sub1120 commented
> > > @sub1120 please have a look and tell me the review so that I can move with other stuffs
> 
> > 
> 
> > Hello @Vinay-Pratap-Singh, Thanks for your active contribution. Sorry, but this PR is too long to review. It is always easier to review and merge small PRs, and If we move this fast, we may end up missing small things behind. Could you please create separate PRs for different sections of UI?
> 
> > 
> 
> > Also, we are planning to setup testing before we move further in UI development. I have already created an issue #73 for it, if you or any of your friend have any idea about "How to setup UI Testing", please have a look upon it.
> 
> 
> 
> I like this idea, but let it slide this one time since it is already done.
> 
> 
> 
> Let's review this and merge and from next time onwards @Vinay-Pratap-Singh please keep the PRs short.

Okay, I will try to review it as soon as possible.

2023-10-20 08:19 UTC, shivamvijaywargi reviewed
Please check the comments.

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/app/contact/page.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
This is great but I would request you to please use the Form component from shadcn UI since we are using it in all other places. Also shadcn UI form component gives zod which is a schema validation library, so please use that for type safety in the form data in the frontend.

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/app/contact/page.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
This is great but I would request you to please use the Form component from shadcn UI since we are using it in all other places. Also shadcn UI form component gives zod which is a schema validation library, so please use that for type safety in the form data in the frontend.

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/app/contact/page.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
Also, since we only need interactivity in the form component, I think we can extract it out into its own separate component and mark only the form component as client instead of marking the entire page as client.

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/app/error.tsx
> +function Error({
May I know the reason for the conversion of arrow function to a regular function?

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/app/not-found.tsx
> +function PageNotFound() {
May I know the reason for the conversion of arrow function to a regular function?

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/components/contact/Breadcrumb.tsx
> +"use client";
May I know why is this marked as a client component?

2023-10-20 08:19 UTC, shivamvijaywargi commented on src/components/course/CourseCard.tsx
> +                {data?.totalEnrollments}K<span>students</span>
You will not get the students data in such a format that you can directly add K all the time to the number, you need to handle this a bit more carefully. Please write a utility function for the conversion or remove it.

2023-10-20 16:34 UTC, Vinay-Pratap-Singh commented
> > @sub1120 please have a look and tell me the review so that I can move with other stuffs
> 
> Hello @Vinay-Pratap-Singh, Thanks for your active contribution. Sorry, but this PR is too long to review. It is always easier to review and merge small PRs, and If we move this fast, we may end up missing small things behind. Could you please create separate PRs for different sections of UI?
> 
> Also, we are planning to setup testing before we move further in UI development. I have already created an issue #73 for it, if you or any of your friend have any idea about "How to setup UI Testing", please have a look upon it.

Thanks @shivamvijaywargi  and @sub1120  for considering it, from next time i will try to make pr for each component.
Also will resolve the comments soon

2023-10-20 16:41 UTC, Vinay-Pratap-Singh commented on src/app/error.tsx
> +function Error({
All files were converted to CRLF for which I had used pnpm fix maybe that modified these things, will check and make them same as it was previously.

2023-10-20 16:42 UTC, Vinay-Pratap-Singh commented on src/app/not-found.tsx
> +function PageNotFound() {
All files were converted to CRLF for which I had used pnpm fix maybe that modified these things, will check and make them same as it was previously.

2023-10-24 13:09 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
implemented zod and shadcn form

2023-10-24 13:11 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
i had implemented the zod schema over there

2023-10-24 13:13 UTC, Vinay-Pratap-Singh commented on src/components/contact/Breadcrumb.tsx
> +"use client";
form is a client component, so i have to tell next js that its client not a server component so that i can use useForm hook over there

2023-10-24 13:16 UTC, Vinay-Pratap-Singh commented on src/components/course/CourseCard.tsx
> +                {data?.totalEnrollments}K<span>students</span>
removed k from the numbers

2023-10-24 13:22 UTC, Vinay-Pratap-Singh commented on src/app/not-found.tsx
> +function PageNotFound() {
I had modified all the asked changes expect the conversion of these normal function to arrow function as whenever i am saving the file of not-found and error it is automatically converted into the normal function to arrow function.
Please have a look at all the other things and if possible these functions can be made as an arrow function from your end or from mine once this auto change thing got fixed.
@shivamvijaywargi @sub1120 please have a look

2023-10-25 12:54 UTC, shivamvijaywargi requested changes
Please check the comments

2023-10-25 12:54 UTC, shivamvijaywargi commented on src/app/contact/page.tsx
> +            <Form {...form}>
As discussed please extract the form component into its own component file so that we can mark it as client instead of marking the entire component as a client component

2023-10-26 04:13 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +            <Form {...form}>
Sperated the form from page and added it as a component. Please have a look and let me know for any further improvement if needed.
@shivamvijaywargi 

Also i am working on signup page so in that should i send 1 PR after completion of the signup page as it a simple and short page having less content over there. Let me know on this one also. @sub1120

2023-10-26 04:21 UTC, sub1120 commented on src/app/contact/page.tsx
> +            <Form {...form}>
I think 1 PR is enough for signUp page. Please go ahead.

2023-10-26 04:51 UTC, shivamvijaywargi commented on src/app/not-found.tsx
> +function PageNotFound() {
No problem if that is the case.

2023-10-26 04:56 UTC, shivamvijaywargi requested changes
Good work until now, please review the last couple of changes and we should be good to go

2023-10-26 04:56 UTC, shivamvijaywargi commented on src/app/contact/page.tsx
> +            <p>1702 Olympic Boulevard Santa Monica, CA 90404</p>
How about we store such constants in a separate file and reuse them in our code so that when we change it in one place it is automatically reflected in every place?

@Vinay-Pratap-Singh  @sub1120

2023-10-26 04:56 UTC, shivamvijaywargi commented on src/components/breadcrumb/Breadcrumb.tsx
> +"use client";
Why are we using use client in this file?

2023-10-26 04:56 UTC, shivamvijaywargi commented on src/components/contact/ContactForm.tsx
> +  firstName: z.string().min(3, {
Please use .trim() before .min() so that empty spaces cannot be passed.

2023-10-26 04:56 UTC, shivamvijaywargi commented on src/components/contact/ContactForm.tsx
> +        <Button type="submit" className="w-full lg:w-fit">
Can we add loading if the form is submitting so that the user cannot click on submit again?

2023-10-26 04:57 UTC, shivamvijaywargi commented on src/components/contact/Breadcrumb.tsx
> +"use client";
But Breadcrumb.tsx file does not use any client side things. Is it really required here?

2023-10-26 09:31 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +            <Form {...form}>
> I think 1 PR is enough for signUp page. Please go ahead.

thanks for the reply will make it within 1 or 2 days.

2023-10-26 09:48 UTC, Vinay-Pratap-Singh commented on src/components/contact/ContactForm.tsx
> +        <Button type="submit" className="w-full lg:w-fit">
added react hook form submitting over there.

2023-10-26 09:49 UTC, Vinay-Pratap-Singh commented on src/components/contact/ContactForm.tsx
> +  firstName: z.string().min(3, {
added trim to all the fields

2023-10-26 09:56 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +            <p>1702 Olympic Boulevard Santa Monica, CA 90404</p>
added the sample data and its interface and made it dynamic, please have a look to it and let me know if any further improvement is required.
@shivamvijaywargi

2023-10-28 04:00 UTC, Vinay-Pratap-Singh commented
@shivamvijaywargi please have a look into it and let me know if any further improvement is required.

2023-10-28 04:42 UTC, shivamvijaywargi commented
@sub1120 please take it over.

2023-10-28 04:54 UTC, sub1120 commented
> @sub1120 please take it over.

checking...

2023-10-28 05:24 UTC, sub1120 commented
@Vinay-Pratap-Singh, please check the few requested UI changes from my side. Apart from that all good. Nice work.

2023-10-28 15:07 UTC, Vinay-Pratap-Singh commented on src/components/contact/Breadcrumb.tsx
> +"use client";
removed it from there

2023-10-28 15:54 UTC, sub1120 commented on src/app/contact/page.tsx
Vinay, below UI looks little different from design (spacing and separator). Could you please compare and check once. For sperator please use shadcn [seperator](https://ui.shadcn.com/docs/components/separator)

| Current                                                                                           | Design                                                                                            |
| ------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| ![image](https://github.com/lmsGenie/client/assets/43786036/845e9ff7-d191-4d4e-8159-c38614618718) | ![image](https://github.com/lmsGenie/client/assets/43786036/6a763638-081d-4025-8101-ab1f6c936830) |

2023-10-28 15:55 UTC, sub1120 commented on src/app/contact/page.tsx
margin from left and right of page is too large. Please compare it with home page(not in design) and lets be consistent.

Note: The figma design provided is made for large screens (width > 1920 px). So we need to think accordingly while developing.

2023-10-28 15:55 UTC, sub1120 commented on src/app/contact/page.tsx
> +  <div>
replace `div` with `main` tag, it is usually preferred to follow

```html
<header />
<main>
  <section></section>
  <section></section>
</main>
<footer />
```

Please let me know, if i am wrong with an example provided by any good resource online.

2023-10-28 15:58 UTC, sub1120 commented on src/app/contact/page.tsx
> +    <main className="flex flex-col-reverse items-center gap-3 border-b-[1px] border-gray-500 py-5 dark:border-gray-800 sm:flex-row sm:px-10 sm:py-0 sm:pt-2 xl:gap-20 xl:px-48 xl:pt-10">
please replace `main` with `section`. It is just a section like other sections.

2023-10-28 15:58 UTC, sub1120 commented on src/app/contact/page.tsx
> +        <Button>
Can we make this button functional for `dev.lmsgenie@gmail.com`.

2023-10-28 15:58 UTC, sub1120 commented on src/app/contact/page.tsx
> +        <div className="space-y-5 bg-white p-2 sm:p-5 lg:p-10">
please replace `div` with `section`. it is usually preferred to follow

```html
<header />
<main>
  <section></section>
  <section></section>
</main>
<footer />
```

2023-10-28 15:59 UTC, sub1120 commented on src/sampledata.ts
> +  email: "test@gmail.com",
Could you please it `dev.lmsgenie@gmail.com`.

2023-10-29 04:23 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
If I will give it a space like the home page the UI will look bad as there is not much content that can consume the space in between, so for the contact page, it is better for us to go as per design.
And also I don't think that in the name of consistency, all the pages should have the same margin and padding. It is a huge project in which there will be requirements for different margins and padding as per the content available for that particular page.
Even if you guys are willing for consistent margin padding for every page by ignoring design then let me know will do it. @shivamvijaywargi @sub1120

2023-10-29 04:25 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +  <div>
done

2023-10-29 04:25 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +    <main className="flex flex-col-reverse items-center gap-3 border-b-[1px] border-gray-500 py-5 dark:border-gray-800 sm:flex-row sm:px-10 sm:py-0 sm:pt-2 xl:gap-20 xl:px-48 xl:pt-10">
done

2023-10-29 04:26 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +        <div className="space-y-5 bg-white p-2 sm:p-5 lg:p-10">
done

2023-10-29 04:27 UTC, Vinay-Pratap-Singh commented on src/sampledata.ts
> +  email: "test@gmail.com",
done

2023-10-29 05:16 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
> +        <Button>
done @sub1120 have a look to all the comments

2023-10-29 05:44 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
done have a look @sub1120

2023-10-29 07:26 UTC, sub1120 commented on src/app/contact/page.tsx
Okay let's go ahead such pages with this margin.

2023-10-29 07:29 UTC, sub1120 commented on src/app/contact/page.tsx
Can we use separator component provided by shandcn instead of border.

2023-10-29 15:16 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
I don't think it is required, if I can do that using the border then why use a separator over there unnecessarily?
Even if you want me to use a separator then can you please provide me any specific reason either in the name of performance, good practice, or from any relevant resource that using a separator is better instead of a border which is an inbuilt property of the CSS.

2023-10-29 15:50 UTC, sub1120 commented on src/app/contact/page.tsx
Generally shandcn components provide better accessibility. 

Check out this separator code to know how it is different from our current implementation.

https://github.com/radix-ui/primitives/blob/main/packages/react/separator/src/Separator.tsx

So let's try whenever possible use shadcn components.

2023-10-30 02:01 UTC, Vinay-Pratap-Singh commented on src/app/contact/page.tsx
Thanks for the reference, I also understand the accessibility part but not convinced for this particular thing that I should remove the border and replace it with the separator code.
Because the argument from your end is not sufficient to which you are giving to change the code.

I accepted the required changes and modified the code as per your concerns which were really good and important but I do not think the same for this.

By the way, I am not going to modify this code, you guys can reject this PR as you guys are the owner and have complete authority over how you want this project to be.

Thanks for all the PRs to which you guys have merged by which I had got a good experience and was an amazing journey. From now onward I will not be able to contribute more to this project.

Thanks to @shivamvijaywargi and @sub1120 for giving me the chance to contribute to this project.

2023-10-30 02:21 UTC, sub1120 commented on src/app/contact/page.tsx
@Vinay-Pratap-Singh we are trying to maintain best practices in this project and accessibility is one of it. If we maintain code standards from the beginning, it will allow other collaborators to follow the same.

I know this PR took more than the usual time for review. But believe us, we are just trying our best to maintain the codebase. You are among the top contributors in this project. We would love to continue with you, but it's totally your choice.🙂

2023-11-08 06:13 UTC, closed without merging